=== KarenFushimi/functree-ng/functree/static/data/example/reference-tree-schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "reference tree",
	"description": "A FuncTree reference tree",
	"type": "object",
	"required": [
		"entry",
		"name",
		"layer"
	],
	"properties": {
		"entry": {
			"description": "Entry id for example K number or Module ids...",
			"type": "string"
		},
		"name": {
			"description": "The display name of the entry",
			"type": "string"
		},
		"layer": {
			"description": "Layer of the object e.g. KO, Module or Pathway",
			"type": "string"
		},
		"children": {
			"description": "Description of the profile",
			"type": "array",
			"items": {
				"$ref": "#"
			}
		}
	}
}

=== KarenFushimi/functree-ng/functree/static/data/example/reference_tree.json
{
  "entry": "example",
  "name": "Example reference",
  "layer": "root",
  "children": [
  {"entry": "map00010",
  "name": "Name of map00010",
  "layer": "L1",
  "children": [
    {
      "entry": "M00001",
      "name": "Name of M00001",
      "layer": "Module",
      "children": [
        {
          "entry": "K00003",
          "name": "Name of K00003",
          "layer": "gene"
        },
        {
          "entry": "K12407",
          "name": "Name of K12407",
          "layer": "gene"
        }
      ]
    },{
      "entry": "M00002",
      "name": "Name of M00002",
      "layer": "Module",
      "children": [
        {
          "entry": "K00844",
          "name": "Name of K00844",
          "layer": "gene"
        },
        {
          "entry": "K12407",
          "name": "name of K12407",
          "layer": "gene"
        }
      ]
    }
  ]
},{
  "entry": "map00012",
  "name": "Name of map00012",
  "layer": "L1",
  "children": [
    {
      "entry": "M00003",
      "name": "Name of M00003",
      "layer": "Module",
      "children": [
        {
          "entry": "K00844",
          "name": "name of K00844",
          "layer": "gene"
        },
        {
          "entry": "K12407",
          "name": "name of K12407",
          "layer": "gene"
        }
      ]
    },{
      "entry": "M00004",
      "name": "name of M00004",
      "layer": "Module",
      "children": [
        {
          "entry": "K00844",
          "name": "Name of K00844",
          "layer": "gene"
        },
        {
          "entry": "K12407",
          "name": "Name of K12407",
          "layer": "gene"
        }
      ]
    }
  ]
}]
}
